src/myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/myfinance-web-dotnet/Models/PlanoContaModel.cs
namespace myfinance_web_netcore.Models
{
    public class PlanoContaModel
    {
        public int? Id { get; set; }
        public string Descricao { get; set; }
        public string Tipo { get; set; }
    }
}

src/myfinance-web-dotnet/Models/TransacaoModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
namespace myfinance_web_netcore.Models
{
    public class TransacaoModel
    {
        public int? Id {
            get; 
            set; 
            }
        public DateTime Data { 
            get; 
            set; 
            }
        public decimal Valor { 
            get; 
            set; 
            }
        public string? Historico { 
            get; 
            set; 
            }
        public int PlanoContaId { 
            get; 
            set; 
            }
        public PlanoContaModel ItemPlanoConta { 
            get; 
            set; 
            }
        public IEnumerable<SelectListItem>? PlanoContas { 
            get; 
            set; 
            }
    }
}

src/myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Privacy()
    {
        return View();
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/myfinance-web-dotnet/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Models;
using myfinance_web_netcore.Domain.Services.Interfaces;

namespace myfinance_web_netcore.Controllers
{
    [Route("[controller]")]
    public class PlanoContaController : Controller
    {
        private readonly ILogger<PlanoContaController> _logger;

        private readonly IPlanoContaService _planoContaService;

        public PlanoContaController(ILogger<PlanoContaController> logger, IPlanoContaService planoContaservice)
        {
            _logger = logger;
            _planoContaService = planoContaservice;
        }

        [HttpGet]
        [Route("Index")]
        public IActionResult Index()
        {
            ViewBag.ListaPlanoConta = _planoContaService.ListarRegistros();
            return View();
        }

        [HttpGet]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public IActionResult Cadastro(int? id)
        {
            if (id != null)
            {
                var registro = _planoContaService.RetornarRegistro((int)id);
                return View(registro);
            }
            return View();
        }

        [HttpPost]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public IActionResult Cadastro(PlanoContaModel model)
        {
            _planoContaService.Salvar(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            _planoContaService.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

src/myfinance-web-dotnet/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Domain.Services.Interfaces;
using myfinance_web_netcore.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_netcore.Controllers
{
    [Route("[controller]")]
    public class TransacaoController : Controller
    {
        private readonly ILogger<TransacaoController> _logger;

        private readonly IPlanoContaService _planoContaservice;
        private readonly ITransacaoService _transacaoService;

        public TransacaoController(
            ILogger<TransacaoController> logger,
            IPlanoContaService planoContaservice,
            ITransacaoService transacaoService)
        {
            _logger = logger;
            _planoContaservice = planoContaservice;
            _transacaoService = transacaoService;
        }

        [HttpGet]
        [Route("Index")]
        public IActionResult Index()
        {
            ViewBag.Transacoes = _transacaoService.ListarRegistros();
            return View();
        }

        [HttpGet]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public IActionResult Cadastro(int? id)
        {
            var model = new TransacaoModel();
            if (id != null)
            {
                model = _transacaoService.RetornarRegistro((int)id);
            }
            var lista = _planoContaservice.ListarRegistros();
            model.PlanoContas = new SelectList(lista, "Id", "Descricao");
            return View(model);
        }

        [HttpPost]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public IActionResult Cadastro(TransacaoModel model)
        {
            _transacaoService.Salvar(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            _transacaoService.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

src/myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row justify-content-center">
    <h1 class="display-4">My finance Web</h1>
    <p>Controle de Finanças pessoais</p>
</div>

src/myfinance-web-dotnet/Views/PlanoConta/Cadastro.cshtml
@model PlanoContaModel

@{
  ViewData["Title"] = "Cadastro de Plano de Contas";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="PlanoConta" asp-action="Cadastro" method="post">
  <div class="container">
    <div class="mb-3">
      <label class="form-label">Descrição</label>
      <input type="hidden" class="form-control" id="Id" asp-for="Id" />
      <input type="text" class="form-control" id="Descricao" asp-for="Descricao" />
    </div>

    <div class="mb-3">
      <label class="form-label">Tipo</label> <br>
      <label>@Html.RadioButtonFor(m => m.Tipo, "D") Despesa</label>
      <label>@Html.RadioButtonFor(m => m.Tipo, "R") Receita</label>
    </div>

    <div>
      <a role="button" href="/PlanoConta/Index" type="button" class="btn btn-secondary">Cancelar</a>
      <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
  </div>
</form>

src/myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
@{
  ViewData["Title"] = "Plano de Contas";
}

<h1>@ViewData["Title"]</h1>

<a role="button" href="../PlanoConta/Cadastro" type="button" class="btn btn-primary btn-lg">Criar item de Plano de
  Conta</a>
<hr />

<table class="table table-white table-striped">
  <thead>
    <tr>
      <th col">Id</th>
      <th col">Descrição</th>
      <th col">Tipo</th>
      <th col"></th>
      <th col"></th>
    </tr>
  </thead>
  <tbody>
    @{
      foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoConta)
      {
        <tr>
          <td>@item.Id</td>
          <td>@item.Descricao</td>
          <td>@item.Tipo</td>
          <td>
            <button type="button" class="btn btn-outline-warning" onclick="Editar(@item.Id.ToString())">Editar</button>
          </td>
          <td>
            <button type="button" class="btn btn-outline-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button>
          </td>
        </tr>
      }
    }
  </tbody>
</table>
<script>
  function Editar(id) {
    window.location.href = "../PlanoConta/Cadastro/" + id
  }
  function Excluir(id) {
    window.location.href = "../PlanoConta/Excluir/" + id
  }
</script>

src/myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/myfinance-web-dotnet/Views/Transacao/Cadastro.cshtml
@model TransacaoModel

@{
    ViewData["Title"] = "Registro de Transação Financeira";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Transacao" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="hidden" class="form-control" id="Id" asp-for="Id" />
            <input type="date" class="form-control" id="Data" asp-for="Data" />
        </div>

        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="text" class="form-control" id="Valor" asp-for="Valor" step="0.01" />
        </div>

        <div class="mb-3">
            <label class="form-label">Item Plano de Conta</label>
            @Html.DropDownListFor(m => m.PlanoContaId, Model.PlanoContas, new{@class="form-select"})
        </div>

        <div class="mb-3">
            <label class="form-label">Histórico</label>
            <input type="text" class="form-control" id="Historico" asp-for="Historico" />
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a role="button" href="/Transacao/Index" type="button" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>

src/myfinance-web-dotnet/Views/Transacao/Index,.cshtml
@{
    ViewData["Title"] = "Transações Financeiras";
}

<h1>@ViewData["Title"]</h1>

<a role="button" href="/Transacao/Cadastro" type="button" class="btn btn-primary btn-lg">Registrar Transação</a>

<hr />

<table class="table table-white table-striped">
    <thead>
        <tr>
            <th col">Id</th>
            <th col">Data</th>
            <th col">Histórico</th>
            <th col">Valor</th>
            <th col">Tipo Operação</th>
            <th col">Plano Conta</th>
            <th col"></th>
            <th col"></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<TransacaoModel>)ViewBag.Transacoes)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Data</td>
                    <td>@item.Historico</td>
                    <td>@item.Valor</td>
                    <td>@item.ItemPlanoConta.Tipo</td>
                    <td>@item.ItemPlanoConta.Descricao</td>
                    <td>
                        <button type="button" class="btn btn-outline-warning"
                            onclick="Editar(@item.Id.ToString())">Editar</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-outline-danger"
                            onclick="Excluir(@item.Id.ToString())">Excluir</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<script>
    function Editar(id) {
        window.location.href = "../Transacao/Cadastro/" + id
    }

    function Excluir(id) {
        window.location.href = "../Transacao/Excluir/" + id
    }
</script>